version: "3.8"

services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  app:
    image: python:3.11-slim
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - REDIS_URL=redis://redis:6379/0
      - REDIS_QUEUE=bot_queue
      - GH_APP_ID=${GH_APP_ID}
      - GH_PRIVATE_KEY=${GH_PRIVATE_KEY}
      - GH_WEBHOOK_SECRET=${GH_WEBHOOK_SECRET}
    depends_on:
      redis:
        condition: service_healthy
    command:
      [
        "sh",
        "-c",
        "apt-get update && apt-get install -y git && pip install -r requirements.txt && python bot_redis_workers/app.py",
      ]

  worker:
    image: python:3.11-slim
    restart: unless-stopped
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - REDIS_URL=redis://redis:6379/0
      - REDIS_QUEUE=bot_queue
      - GH_APP_ID=${GH_APP_ID}
      - GH_PRIVATE_KEY=${GH_PRIVATE_KEY}
    depends_on:
      redis:
        condition: service_healthy
    command:
      [
        "sh",
        "-c",
        "apt-get update && apt-get install -y git && pip install -r requirements.txt && python bot_redis_workers/worker.py",
      ]
    deploy:
      replicas: 2

volumes:
  redis_data:
